import { PERMISSIONS } from "./permissions.js";
import { ROLES } from "./roles.js";

export const ROLE_PERMISSIONS = {
  [ROLES.SUPER_ADMIN]: Object.values(PERMISSIONS),

  [ROLES.OWNER]: Object.values(PERMISSIONS),

  [ROLES.MANAGER]: [
    PERMISSIONS.BOOKING_CREATE,
    PERMISSIONS.BOOKING_READ,
    PERMISSIONS.BOOKING_UPDATE,
    PERMISSIONS.BOOKING_DELETE,

    PERMISSIONS.CUSTOMER_CREATE,
    PERMISSIONS.CUSTOMER_READ,
    PERMISSIONS.CUSTOMER_UPDATE,
    PERMISSIONS.CUSTOMER_DELETE,

    PERMISSIONS.STAFF_CREATE,
    PERMISSIONS.STAFF_READ,
    PERMISSIONS.STAFF_UPDATE,
    PERMISSIONS.STAFF_DELETE,

    PERMISSIONS.SERVICE_CREATE,
    PERMISSIONS.SERVICE_READ,
    PERMISSIONS.SERVICE_UPDATE,
    PERMISSIONS.SERVICE_DELETE,

    PERMISSIONS.BRANCH_READ,

    PERMISSIONS.SETTINGS_READ,

    PERMISSIONS.INVOICE_CREATE,
    PERMISSIONS.INVOICE_READ,

    PERMISSIONS.PAYMENT_READ,
  ],

  [ROLES.RECEPTIONIST]: [
    PERMISSIONS.BOOKING_CREATE,
    PERMISSIONS.BOOKING_READ,
    PERMISSIONS.BOOKING_UPDATE,

    PERMISSIONS.CUSTOMER_CREATE,
    PERMISSIONS.CUSTOMER_READ,
    PERMISSIONS.CUSTOMER_UPDATE,

    PERMISSIONS.SERVICE_READ,

    PERMISSIONS.STAFF_READ,

    PERMISSIONS.BRANCH_READ,

    PERMISSIONS.INVOICE_CREATE,
    PERMISSIONS.INVOICE_READ,

    PERMISSIONS.PAYMENT_CREATE,
    PERMISSIONS.PAYMENT_READ,
  ],

  [ROLES.STAFF]: [
    PERMISSIONS.BOOKING_READ,
    PERMISSIONS.BOOKING_UPDATE,

    PERMISSIONS.CUSTOMER_READ,

    PERMISSIONS.SERVICE_READ,

    PERMISSIONS.STAFF_READ,

    PERMISSIONS.BRANCH_READ,
  ],
};